# basic
[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "Shougo/vimproc.vim"
build = "make"

[[plugins]]
repo = "Shougo/vimshell.vim"

# theme
[[plugins]]
repo = "arcticicestudio/nord-vim"

[[plugins]]
repo = "itchyny/lightline.vim"
hook_add = '''
    let g:lightline = {
    \ 'colorscheme': 'wombat',
    \ 'active': {
    \   'left': [ [ 'mode', 'paste' ],
    \             [ 'readonly', 'filename', 'modified' ],
    \             [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok' ] ],
    \ },
    \ }
'''

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['lightline.vim', 'ale']
hook_add = '''
let g:lightline.component_expand = {
      \  'linter_checking': 'lightline#ale#checking',
      \  'linter_warnings': 'lightline#ale#warnings',
      \  'linter_errors': 'lightline#ale#errors',
      \  'linter_ok': 'lightline#ale#ok',
      \ }
let g:lightline.component_type = {
      \     'linter_checking': 'left',
      \     'linter_warnings': 'warning',
      \     'linter_errors': 'error',
      \     'linter_ok': 'left',
      \ }
'''

# function
## for little lazy
[[plugins]]
repo = "Townk/vim-autoclose"

[[plugins]]
repo = "bronson/vim-trailing-whitespace"

[[plugins]]
repo = "kana/vim-submode"

[[plugins]]
repo = "tpope/vim-surround"

## git
[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = "airblade/vim-gitgutter"

## listing files
[[plugins]]
repo = "scrooloose/nerdtree"

[[plugins]]
repo = "Xuyuanp/nerdtree-git-plugin"

[[plugins]]
repo = "jistr/vim-nerdtree-tabs"

# syntax check
[[plugins]]
repo = "w0rp/ale"

# completion
## language server
[[plugins]]
repo = "prabirshrestha/async.vim"

[[plugins]]
repo = "prabirshrestha/vim-lsp"

[[plugins]]
repo = "prabirshrestha/asyncomplete.vim"

[[plugins]]
repo = "prabirshrestha/asyncomplete-lsp.vim"

[[plugins]]
repo = "natebosch/vim-lsc"

## javascript
[[plugins]]
repo = "Valloric/YouCompleteMe"
merged = 0
# cd .cache/dein/repos/.../YouCompleteMe
# git subomodule update --init --recursive
# /usr/bin/python install.py

## nginx
[[plugins]]
repo = "chr4/nginx.vim"

# syntax highlight
[[plugins]]
repo = "dag/vim-fish"

