# basic
[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "Shougo/vimproc.vim"
build = "make"

# theme
[[plugins]]
repo = "arcticicestudio/nord-vim"

[[plugins]]
repo = "vim-airline/vim-airline"
depends = ["vim-airline-themes"]

[[plugins]]
repo = "vim-airline/vim-airline-themes"

# function
## for little lazy
[[plugins]]
repo = "Townk/vim-autoclose"

[[plugins]]
repo = "bronson/vim-trailing-whitespace"

[[plugins]]
repo = "kana/vim-submode"

## git
[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = "airblade/vim-gitgutter"

## listing files
[[plugins]]
repo = "scrooloose/nerdtree"

[[plugins]]
repo = "Xuyuanp/nerdtree-git-plugin"

[[plugins]]
repo = "jistr/vim-nerdtree-tabs"

# completion
## language server
[[plugins]]
repo = "prabirshrestha/async.vim"

[[plugins]]
repo = "prabirshrestha/vim-lsp"

[[plugins]]
repo = "prabirshrestha/asyncomplete.vim"

[[plugins]]
repo = "prabirshrestha/asyncomplete-lsp.vim"

[[plugins]]
repo = "natebosch/vim-lsc"

## typescript
[[plugins]]
repo = "leafgarland/typescript-vim"

[[plugins]]
repo = "Quramy/tsuquyomi"
on_ft = ["typescript"]

## nginx
[[plugins]]
repo = "chr4/nginx.vim"

# syntax highlight
[[plugins]]
repo = "dag/vim-fish"

