[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "Shougo/vimproc.vim"

[[plugins]]
repo = "vim-airline/vim-airline"
depends = ["vim-airline-themes"]

[[plugins]]
repo = "vim-airline/vim-airline-themes"

[[plugins]]
repo = "Townk/vim-autoclose"

[[plugins]]
repo = "bronson/vim-trailing-whitespace"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "leafgarland/typescript-vim"

[[plugins]]
repo = "Quramy/tsuquyomi"
on_ft = ["typescript"]

[[plugins]]
repo = "Shougo/vimproc"
build = "make"

[[plugins]]
repo = "scrooloose/nerdtree"

[[plugins]]
repo = "Xuyuanp/nerdtree-git-plugin"

[[plugins]]
repo = "jistr/vim-nerdtree-tabs"

[[plugins]]
repo = "chr4/nginx.vim"
