## nginx
[[plugins]]
repo = 'chr4/nginx.vim'
on_ft = 'conf'

# syntax highlight
[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

# syntax Docker
[[plugins]]
repo = 'ekalinin/Dockerfile.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = 'go'

[[plugins]]
repo = 'mattn/vim-goimpl'
on_ft = 'go'
