# basic
[[plugins]]
repo = 'Shougo/dein.vim'

# theme
[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
  colorscheme nord
'''
  #autocmd ColorScheme * highlight LineNr ctermbg=239
  #autocmd ColorScheme * highlight LineNr ctermfg=252
  #set fillchars+=vert:\ 

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
  \ 'colorscheme': 'wombat',
  \ 'active': {
  \   'left': [ [ 'mode', 'paste' ],
  \             [ 'readonly', 'filename', 'modified' ],
  \             [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok' ] ],
  \ },
  \ }
'''

# function
## for little lazy
[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'tpope/vim-surround'

# completion
## language server
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
  autocmd BufWritePost *.js :call system('test -e .eslintrc* && eslint . --fix')|:e
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
  let g:lsp_settings_servers_dir='~/.nvim/cache/lsp-servers'
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

# prettier
[[plugins]]
repo = 'prettier/vim-prettier'
build = 'npm install'
on_ft = ['json', 'markdown', 'yaml', 'html']
hook_source = '''
  let g:prettier#autoformat = 0
  let g:prettier#quickfix_enabled = 0
  autocmd BufWritePre *.json,*.md PrettierAsync
'''

# denite
[[plugins]]
repo = 'Shougo/denite.nvim'

# git
[[plugins]]
repo = 'iberianpig/tig-explorer.vim'

[[plugins]]
repo = "airblade/vim-gitgutter"

# nerdtree
### listing files
[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

# debugger
[[plugins]]
repo = 'sebdah/vim-delve'

# snippet
#[[plugins]]
#repo = 'Shougo/deoppet.nvim'
#hook_add = '''
#    imap <C-k>  <Plug>(deoppet_expand)
#    imap <C-f>  <Plug>(deoppet_jump_forward)
#    imap <C-b>  <Plug>(deoppet_jump_backward)
#    smap <C-f>  <Plug>(deoppet_jump_forward)
#    smap <C-b>  <Plug>(deoppet_jump_backward)
#
#    call deoppet#initialize()
#    call deoppet#custom#option('snippets',
#    \ map(globpath(&runtimepath, 'neosnippets', 1, 1),
#    \     "{ 'path': v:val }"))
#'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'hashivim/vim-terraform'
