" minimum
set encoding=utf-8
set number
set ruler
set tabstop=4
set expandtab
set smartindent
set autoindent
set shiftwidth=4
set backspace=indent,eol,start
set clipboard=unnamed
set wildignore+=node_modules/**
set switchbuf+=usetab,newtab
set incsearch
set hlsearch
set ignorecase
set smartcase
set showmatch
set fillchars+=vert:\|
set background=dark
set t_Co=256
set mouse=a
