# syntax highlight
## kotlin
[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = 'kotlin'

## Dockerfile
[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['Dockerfile', 'docker-compose']

# lsp
## typescript
[[plugins]]
repo = 'ryanolsonx/vim-lsp-typescript'
on_ft = ['typescript']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['typescript']


## go
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
